# Build on Microsoft Windows and package to .jar

name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Clean previous build
      run: mvn clean
    - name: Build and package
      run: mvn compile package --file pom.xml
    - run: mkdir staging && cp *win.jar staging
    - uses: actions/upload-artifact@v1
      with:
        name: Binary
        path: staging
